updated doc section

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -431,45 +431,81 @@ jobs:
     needs: [docs-style, revn-variations]
     runs-on: public-ubuntu-latest-8-cores
     steps:
-      - name: Set docker image version env variable
-        run: echo "DOCKER_IMAGE_VERSION=${{needs.revn-variations.outputs.default}}" >> $GITHUB_ENV
-
-      - name: Set AWP_ROOT env variable
-        run: echo "AWP_ROOT${{ needs.revn-variations.outputs.test_lic }}=/install/ansys_inc/v${{ needs.revn-variations.outputs.test_lic }}" >> $GITHUB_ENV
+      - name: Install Git and checkout project
+        uses: actions/checkout@v4
         
-      - name: Login in Github Container registry
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Pull, launch, and validate Mechanical service
-        env:
-          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
-          MECHANICAL_IMAGE: ${{ env.DOCKER_PACKAGE }}:${{ env.DOCKER_IMAGE_VERSION }}
+      - name: Set up Python
         run: |
-          echo CPU info
-          lscpu
-          docker pull ${{ env.MECHANICAL_IMAGE }}
-          docker run --restart always --name ${{ env.DOCKER_MECH_CONTAINER_NAME }} -e ANSYSLMD_LICENSE_FILE=1055@${{ env.LICENSE_SERVER }} -e AWP_ROOT${{ needs.revn-variations.outputs.test_lic }}=/install/ansys_inc/v${{ needs.revn-variations.outputs.test_lic }} -p ${{ env.PYMECHANICAL_PORT }}:10000 ${{ env.MECHANICAL_IMAGE }} > log.txt &
-          grep -q 'WB Initialize Done' <(timeout 60 tail -f log.txt)
+          apt update
+          apt install -y python3.9 python3-pip
+          ln -s /usr/bin/python3.9 /usr/bin/python
+          python -m pip install --upgrade pip
+          python --version
+          pip3 --version
 
-      - name: Run Ansys documentation building action
-        uses: ansys/actions/doc-build@v4
-        with:
-          python-version: ${{ env.MAIN_PYTHON_VERSION }}
-          dependencies: "pandoc"
+      - name: Install system dependencies
+        run: |
+          apt update
+          apt install -y sudo curl lsb-release
+          apt install -y zip pandoc libgl1-mesa-glx mesa-utils xvfb texlive-latex-extra latexmk nodejs npm graphviz
+          apt install -y tini
+          # pip3 install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org
+          npm install -g @mermaid-js/mermaid-cli
 
-      - name: Get Mechanical container logs
-        if: always()
-        run: docker logs ${{ env.DOCKER_MECH_CONTAINER_NAME }} > mechanical_documentation_log.txt 2>&1
+      - name: "Install Python library"
+        shell: bash
+        run: |
+          python -m pip install .
 
-      - name: Upload container logs
+      - name: Retrieve PyMechanial version
+        run: |
+          echo "PYMECHANICAL_VERSION=$(python -c 'from ansys.mechanical.core import __version__; print(__version__)')" >> $GITHUB_ENV
+          echo "PyMechanical version is: $(python -c "from ansys.mechanical.core import __version__; print(__version__)")"
+        id: version
+
+      - name: Set environment variable
+        run: echo "ANSYSCL${{ needs.revn-variations.outputs.test_lic }}_DIR=/install/ansys_inc/v${{ needs.revn-variations.outputs.test_lic }}/licensingclient" >> $GITHUB_ENV
+
+      - name: Build docs
+        env:
+          SPHINXOPTS: '-j auto'
+          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
+          ANSYSLMD_LICENSE_FILE: 1055@${{ secrets.LICENSE_SERVER }}
+          ANSYS_WORKBENCH_LOGGING_FILTER_LEVEL: 0
+        run: |
+          xvfb-run /install/ansys_inc/v${{ needs.revn-variations.outputs.test_lic }}/aisol/.workbench_lite make -C doc html > doc_build_output.txt 2>&1 || true
+          cat doc_build_output.txt
+          #
+          # Check if "build succeeded" string is present in doc_build_output.txt
+          #
+          if grep -q "build succeeded" doc_build_output.txt; then
+            echo "Documentation building succeeded"
+            exit 0
+          else
+            echo "Documentation building failed"
+            exit 1
+          fi
+
+      - name: Upload HTML Documentation
         uses: actions/upload-artifact@v3
         with:
-          name: mechanical_documentation_log
-          path: mechanical_documentation_log.txt
+          name: documentation-html
+          path: doc/_build/html
+          retention-days: 7
+
+      - name: "Upload PDF documentation artifact"
+        uses: actions/upload-artifact@v3
+        with:
+          name: documentation-pdf
+          path: doc/_build/latex/*.pdf
+          retention-days: 7
+
+      - name: "Upload JSON documentation artifact"
+        uses: actions/upload-artifact@v3
+        if: inputs.skip-json-build == 'false'
+        with:
+          name: documentation-json
+          path: doc/_build/json
           retention-days: 7
 
   coverage:
