parentheses around command

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -281,7 +281,7 @@ jobs:
           NUM_CORES: 1
         shell: bash
         run: |
-          timeout 300 nohup xvfb-run /install/ansys_inc/v${{ needs.revn-variations.outputs.dev_revn }}/aisol/.workbench_lite pytest -m embedding > pytest_output.txt || true &
+          (timeout 300 nohup xvfb-run /install/ansys_inc/v${{ needs.revn-variations.outputs.dev_revn }}/aisol/.workbench_lite pytest -m embedding > pytest_output.txt &) || true
           wait $!
 
           cat pytest_output.txt
@@ -292,13 +292,13 @@ jobs:
           output=$(grep -c "FAILED" pytest_output.txt)
           echo "output: $output"
 
-          # if [ $output -eq 0 ]; then
-          #   echo "Pytest execution succeeded"
-          #   exit 0
-          # else
-          #   echo "Pytest execution failed"
-          #   exit 1
-          # fi
+          if [ $output -eq 0 ]; then
+            echo "Pytest execution succeeded"
+            exit 0
+          else
+            echo "Pytest execution failed"
+            exit 1
+          fi
 
       - name: Upload coverage results
         uses: actions/upload-artifact@v3
