add doc pdf build

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -454,28 +454,43 @@ jobs:
           ANSYSLMD_LICENSE_FILE: 1055@${{ secrets.LICENSE_SERVER }}
           ANSYS_WORKBENCH_LOGGING_FILTER_LEVEL: 0
         run: |
+          # Create doc html and pdf, and validate it passed
+          validate_output() {
+            # $1 is the file we are checking
+            cat $1
+            #
+            # Check if "build succeeded" string is present in doc_build_output.txt
+            #
+            if grep -q "build succeeded" $1; then
+              echo "Documentation building succeeded"
+            else
+              echo "Documentation building failed"
+              exit 1
+            fi
+          }
+           
           # Need to unset PYMECHANICAL_PORT and PYMECHANICAL_START_INSTANCE when running code containing remote sessions
           unset PYMECHANICAL_PORT
           unset PYMECHANICAL_START_INSTANCE
           
           xvfb-run mechanical-env make -C doc html > doc_build_output.txt 2>&1 || true
-          cat doc_build_output.txt
-          #
-          # Check if "build succeeded" string is present in doc_build_output.txt
-          #
-          if grep -q "build succeeded" doc_build_output.txt; then
-            echo "Documentation building succeeded"
-            exit 0
-          else
-            echo "Documentation building failed"
-            exit 1
-          fi
+          validate_output doc_build_output.txt
+          
+          xvfb-run mechanical-env make -C doc pdf > doc_pdf_output.txt 2>&1 || true
+          validate_output doc_pdf_output.txt
 
       - name: Upload HTML Documentation
         uses: actions/upload-artifact@v3
         with:
           name: documentation-html
           path: doc/_build/html
+          retention-days: 7
+
+      - name: Upload PDF Documentation
+        uses: actions/upload-artifact@v3
+        with:
+          name: documentation-pdf
+          path: doc/_build/latex/doc.pdf
           retention-days: 7
 
   coverage:
