test xvfb

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -646,6 +646,20 @@ jobs:
         run: |
           . /env/bin/activate
           # Make html or pdf doc
+          if ! command -v Xvfb &> /dev/null; then
+              echo "Xvfb not found. Installing..."
+              apt-get update && apt-get install -y xvfb
+          fi
+
+          # Check for existing Xvfb processes
+          if pgrep -x "Xvfb" > /dev/null; then
+              echo "Xvfb is already running. Using existing instance."
+              DISPLAY=:99
+          else
+              # Start Xvfb with delay for stability
+              (Xvfb :99 &) && sleep 2
+              export DISPLAY=:99
+          fi
           make_doc() {
             # $1 is the type of file we are creating (html or pdf)
 
