only run pytest no file redirect

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -280,18 +280,20 @@ jobs:
           ANSYS_WORKBENCH_LOGGING_FILTER_LEVEL: 2
           NUM_CORES: 1
         run: |
-          xvfb-run mechanical-env pytest -m embedding -s > pytest_output.txt || true
+          xvfb-run mechanical-env pytest -m embedding -s || true
 
-          cat pytest_output.txt
-          # Check if failure occurred
-          output=$(grep -c "FAILURES" pytest_output.txt || true)
-          if [ $output -eq 0 ]; then
-            echo "Pytest execution succeeded"
-            exit 0
-          else
-            echo "Pytest execution failed"
-            exit 1
-          fi
+          # xvfb-run mechanical-env pytest -m embedding -s > pytest_output.txt || true
+
+          # cat pytest_output.txt
+          # # Check if failure occurred
+          # output=$(grep -c "FAILURES" pytest_output.txt || true)
+          # if [ $output -eq 0 ]; then
+          #   echo "Pytest execution succeeded"
+          #   exit 0
+          # else
+          #   echo "Pytest execution failed"
+          #   exit 1
+          # fi
 
       - name: Upload coverage results
         uses: actions/upload-artifact@v4
