remove output check

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -281,18 +281,17 @@ jobs:
           NUM_CORES: 1
         shell: bash
         run: |
-          trap "" SIGABRT
           nohup xvfb-run /install/ansys_inc/v${{ needs.revn-variations.outputs.dev_revn }}/aisol/.workbench_lite pytest -m embedding
 
           # Check if failure occurred
-          output=$(grep -c "FAILURES" nohup.out)
-          if [ $output -eq 0 ]; then
-            echo "Pytest execution succeeded"
-            exit 0
-          else
-            echo "Pytest execution failed"
-            exit 1
-          fi
+          # output=$(grep -c "FAILURES" nohup.out)
+          # if [ $output -eq 0 ]; then
+          #   echo "Pytest execution succeeded"
+          #   exit 0
+          # else
+          #   echo "Pytest execution failed"
+          #   exit 1
+          # fi
 
       - name: Upload coverage results
         uses: actions/upload-artifact@v3
