py and pip setup

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -49,27 +49,54 @@ jobs:
         python-version: ['3.8', '3.9', '3.10', '3.11']
 
     steps:
-      - uses: actions/checkout@v3
-      - name: apt update
-        run: |
-         apt update 
-
-      - uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-      - run: |
-          python --version
 
       - uses: actions/checkout@v4
+      - name: Set up python and pip
+        run: |
+         apt update
+         apt install software-properties-common -y
+         add-apt-repository ppa:deadsnakes/ppa -y
+         apt install python${{ matrix.python-version }} -y
+         apt install python3-pip
+         ln -s /usr/bin/python${{ matrix.python-version }} /usr/bin/python
+         apt install python${{ matrix.python-version }}-venv -y
+         python -m ensurepip --default-pip
+         python --version
+         pip --version
+
       - name: Install dependencies
         run: |
           apt update
           apt install -y lsb-release
-          apt install -y python3-pip
-          apt install -y python3.8-venv
           pip3 install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org pip setuptools
           pip3 install --upgrade pip flit
 
-      - name: checking py version
+      - name: Install packages for testing
         run: |
-          py -0p
+          pip install .[tests]
+
+          - name: Set environment variable
+          run: echo "ANSYSCL${{ needs.revn-variations.outputs.test_lic }}_DIR=/install/ansys_inc/v${{ needs.revn-variations.outputs.test_lic }}/licensingclient" >> $GITHUB_ENV
+  
+      - name: Unit Testing and coverage
+        env:
+          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
+          ANSYSLMD_LICENSE_FILE: 1055@${{ secrets.LICENSE_SERVER }}
+          ANSYS_WORKBENCH_LOGGING_CONSOLE: 0
+          ANSYS_WORKBENCH_LOGGING: 0
+          ANSYS_WORKBENCH_LOGGING_FILTER_LEVEL: 2
+          NUM_CORES: 1
+        run: |
+          /install/ansys_inc/v${{ needs.revn-variations.outputs.test_lic }}/aisol/.workbench_lite pytest -m embedding -k logging > pytest_output.txt || true
+          cat pytest_output.txt
+          #
+          # Check if failure occurred
+          #
+          output=$(grep -c "FAILURES" pytest_output.txt || true)
+          if [ $output -eq 0 ]; then
+            echo "Pytest execution succeeded"
+            exit 0
+          else
+            echo "Pytest execution failed"
+            exit 1
+          fi
